[package]
name = "kd-core"
version.workspace = true
edition.workspace = true

[dependencies]
kd-encoder.path = "../kd-encoder"
kd-network.path = "../kd-network"

bytes.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
